apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
    type: backend-app
spec:
  type: NodePort
  ports:
   - targetPort: 8080
     port: 8080
     nodePort: 30002
  selector:
    title: my-pod
    type: web-app
